-- Create the table
create table todos (
  id bigint generated by default as identity primary key,
  text text not null,
  completed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
-- For this simple demo without user authentication, we'll allow public access.
-- IN PRODUCTION, YOU SHOULD USE PROPER AUTHENTICATION.
alter table todos enable row level security;

create policy "Allow public read access"
on todos for select
to anon
using (true);

create policy "Allow public insert access"
on todos for insert
to anon
with check (true);

create policy "Allow public update access"
on todos for update
to anon
using (true);

create policy "Allow public delete access"
on todos for delete
to anon
using (true);
